### ISSUE TITLE
[Insight] Database queries should use parameter binding - in login/index.php, line 10

### ISSUE THREAD

**Issue by owenvoke** [PXgamer/kastatus#2]
**[in login/index.php, line 10](https://github.com/PXgamer/kastatus/blob/4307f760d60b06996ae9d1e67c725ba6eeab95c0/login/index.php#L10)**

> If provided by the user, the value of `mysqli_real_escape_string($db_conn, $_POST['username'])` may allow an SQL injection attack. Avoid concatenating parameters to SQL query strings, and use parameter binding instead.

``` php
      include '../head.php';
      include '../backend/funcs.php';
      $db_conn = \funcs\Functions::conn();

      if (isset($_POST['login']) && $_POST['username'] !== '' && $_POST['password'] !== '') {
          $sql = "SELECT password FROM `users` WHERE username='".mysqli_real_escape_string($db_conn, $_POST['username'])."'";
          $res = \funcs\Functions::query($db_conn, $sql);
          while ($row = mysqli_fetch_assoc($res)) {
              $hash = $row['password'];
          }
          $verified = password_verify($_POST['password'], $hash);
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/d6409699-234c-451a-8733-48a43a5f22f4/analyses/2)_

**Comment by mracos** [comment]
giving it a shot!
